<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Keluarga;
use MatanYadaev\EloquentSpatial\Objects\Point;
use Carbon\Carbon;

class KeluargaKalbarSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $keluargaData = [
            // KOTA PONTIANAK (8 keluarga)
            [
                'no_kk' => '6171010101240001',
                'nama_kepala_keluarga' => 'Budi Santoso',
                'alamat' => 'Jl. Gajah Mada No. 123',
                'rt' => '01', 'rw' => '02',
                'kelurahan' => 'Sungai Bangkong',
                'kecamatan' => 'Pontianak Kota',
                'kota' => 'Pontianak',
                'provinsi' => 'Kalimantan Barat',
                'kode_pos' => '78113',
                'status_ekonomi' => 'sangat_miskin',
                'penghasilan_bulanan' => 800000.00,
                'jumlah_anggota' => 4,
                'keterangan' => 'Kepala keluarga bekerja sebagai buruh harian lepas',
                'latitude' => -0.025851, 'longitude' => 109.342003,
                'koordinat_updated_at' => now(),
                'status_verifikasi' => 'terverifikasi',
                'tanggal_verifikasi' => Carbon::now()->subDays(30),
                'verifikator_id' => 1,
                'catatan_verifikasi' => 'Data telah diverifikasi dan sesuai dengan kondisi lapangan',
                'is_active' => true
            ],
            [
                'no_kk' => '6171010101240002',
                'nama_kepala_keluarga' => 'Siti Aminah',
                'alamat' => 'Jl. Ahmad Yani No. 45',
                'rt' => '03', 'rw' => '01',
                'kelurahan' => 'Benua Melayu Darat',
                'kecamatan' => 'Pontianak Selatan',
                'kota' => 'Pontianak',
                'provinsi' => 'Kalimantan Barat',
                'kode_pos' => '78124',
                'status_ekonomi' => 'miskin',
                'penghasilan_bulanan' => 1200000.00,
                'jumlah_anggota' => 5,
                'keterangan' => 'Ibu rumah tangga dengan suami bekerja sebagai tukang ojek',
                'latitude' => -0.030000, 'longitude' => 109.330000,
                'koordinat_updated_at' => now(),
                'status_verifikasi' => 'terverifikasi',
                'tanggal_verifikasi' => Carbon::now()->subDays(25),
                'verifikator_id' => 1,
                'catatan_verifikasi' => 'Keluarga memiliki 3 anak usia sekolah',
                'is_active' => true
            ],
            [
                'no_kk' => '6171010101240003',
                'nama_kepala_keluarga' => 'Ahmad Hidayat',
                'alamat' => 'Jl. Sultan Abdurrahman No. 78',
                'rt' => '05', 'rw' => '03',
                'kelurahan' => 'Akcaya',
                'kecamatan' => 'Pontianak Utara',
                'kota' => 'Pontianak',
                'provinsi' => 'Kalimantan Barat',
                'kode_pos' => '78232',
                'status_ekonomi' => 'rentan_miskin',
                'penghasilan_bulanan' => 1800000.00,
                'jumlah_anggota' => 3,
                'keterangan' => 'Bekerja sebagai pedagang kecil di pasar tradisional',
                'latitude' => -0.010000, 'longitude' => 109.320000,
                'koordinat_updated_at' => now(),
                'status_verifikasi' => 'terverifikasi',
                'tanggal_verifikasi' => Carbon::now()->subDays(20),
                'verifikator_id' => 1,
                'catatan_verifikasi' => 'Penghasilan tidak stabil, tergantung musim',
                'is_active' => true
            ],
            [
                'no_kk' => '6171010101240004',
                'nama_kepala_keluarga' => 'Maria Theresia',
                'alamat' => 'Jl. Diponegoro No. 156',
                'rt' => '02', 'rw' => '04',
                'kelurahan' => 'Darat Sekip',
                'kecamatan' => 'Pontianak Kota',
                'kota' => 'Pontianak',
                'provinsi' => 'Kalimantan Barat',
                'kode_pos' => '78113',
                'status_ekonomi' => 'kurang_mampu',
                'penghasilan_bulanan' => 2200000.00,
                'jumlah_anggota' => 6,
                'keterangan' => 'Keluarga besar dengan 4 anak, suami bekerja sebagai sopir angkot',
                'latitude' => -0.035000, 'longitude' => 109.345000,
                'koordinat_updated_at' => now(),
                'status_verifikasi' => 'terverifikasi',
                'tanggal_verifikasi' => Carbon::now()->subDays(15),
                'verifikator_id' => 1,
                'catatan_verifikasi' => 'Memiliki tanggungan anak yang banyak',
                'is_active' => true
            ],
            [
                'no_kk' => '6171010101240005',
                'nama_kepala_keluarga' => 'Rahmat Hidayat',
                'alamat' => 'Jl. Parit H. Husin II No. 89',
                'rt' => '04', 'rw' => '02',
                'kelurahan' => 'Parit Tokaya',
                'kecamatan' => 'Pontianak Selatan',
                'kota' => 'Pontianak',
                'provinsi' => 'Kalimantan Barat',
                'kode_pos' => '78124',
                'status_ekonomi' => 'sangat_miskin',
                'penghasilan_bulanan' => 750000.00,
                'jumlah_anggota' => 7,
                'keterangan' => 'Pemulung dengan 5 anak',
                'latitude' => -0.040000, 'longitude' => 109.325000,
                'koordinat_updated_at' => now(),
                'status_verifikasi' => 'terverifikasi',
                'tanggal_verifikasi' => Carbon::now()->subDays(35),
                'verifikator_id' => 1,
                'catatan_verifikasi' => 'Keluarga sangat membutuhkan bantuan',
                'is_active' => true
            ],
            [
                'no_kk' => '6171010101240006',
                'nama_kepala_keluarga' => 'Dewi Sartika',
                'alamat' => 'Jl. Sungai Jawi Dalam No. 234',
                'rt' => '01', 'rw' => '03',
                'kelurahan' => 'Sungai Jawi Dalam',
                'kecamatan' => 'Pontianak Barat',
                'kota' => 'Pontianak',
                'provinsi' => 'Kalimantan Barat',
                'kode_pos' => '78117',
                'status_ekonomi' => 'miskin',
                'penghasilan_bulanan' => 1100000.00,
                'jumlah_anggota' => 4,
                'keterangan' => 'Janda dengan 2 anak, bekerja sebagai penjual sayur',
                'latitude' => -0.015000, 'longitude' => 109.315000,
                'koordinat_updated_at' => now(),
                'status_verifikasi' => 'terverifikasi',
                'tanggal_verifikasi' => Carbon::now()->subDays(28),
                'verifikator_id' => 1,
                'catatan_verifikasi' => 'Single parent membutuhkan perhatian khusus',
                'is_active' => true
            ],
            [
                'no_kk' => '6171010101240007',
                'nama_kepala_keluarga' => 'Agus Salim',
                'alamat' => 'Jl. Bansir Darat No. 67',
                'rt' => '03', 'rw' => '01',
                'kelurahan' => 'Bansir Darat',
                'kecamatan' => 'Pontianak Tenggara',
                'kota' => 'Pontianak',
                'provinsi' => 'Kalimantan Barat',
                'kode_pos' => '78232',
                'status_ekonomi' => 'rentan_miskin',
                'penghasilan_bulanan' => 1650000.00,
                'jumlah_anggota' => 5,
                'keterangan' => 'Tukang bangunan dengan penghasilan tidak tetap',
                'latitude' => -0.020000, 'longitude' => 109.355000,
                'koordinat_updated_at' => now(),
                'status_verifikasi' => 'terverifikasi',
                'tanggal_verifikasi' => Carbon::now()->subDays(22),
                'verifikator_id' => 1,
                'catatan_verifikasi' => 'Penghasilan bergantung pada proyek bangunan',
                'is_active' => true
            ],
            [
                'no_kk' => '6171010101240008',
                'nama_kepala_keluarga' => 'Fatimah Zahra',
                'alamat' => 'Jl. Tanjung Hulu No. 145',
                'rt' => '02', 'rw' => '05',
                'kelurahan' => 'Tanjung Hulu',
                'kecamatan' => 'Pontianak Timur',
                'kota' => 'Pontianak',
                'provinsi' => 'Kalimantan Barat',
                'kode_pos' => '78243',
                'status_ekonomi' => 'kurang_mampu',
                'penghasilan_bulanan' => 2000000.00,
                'jumlah_anggota' => 3,
                'keterangan' => 'Guru honorer dengan suami bekerja sebagai security',
                'latitude' => -0.005000, 'longitude' => 109.365000,
                'koordinat_updated_at' => now(),
                'status_verifikasi' => 'terverifikasi',
                'tanggal_verifikasi' => Carbon::now()->subDays(18),
                'verifikator_id' => 1,
                'catatan_verifikasi' => 'Keluarga dengan penghasilan ganda namun terbatas',
                'is_active' => true
            ],

            // KOTA SINGKAWANG (5 keluarga)
            [
                'no_kk' => '6172010101240009',
                'nama_kepala_keluarga' => 'Tan Ah Kiong',
                'alamat' => 'Jl. Niaga No. 89',
                'rt' => '01', 'rw' => '01',
                'kelurahan' => 'Pasiran',
                'kecamatan' => 'Singkawang Barat',
                'kota' => 'Singkawang',
                'provinsi' => 'Kalimantan Barat',
                'kode_pos' => '79123',
                'status_ekonomi' => 'sangat_miskin',
                'penghasilan_bulanan' => 900000.00,
                'jumlah_anggota' => 4,
                'keterangan' => 'Bekerja sebagai nelayan tradisional',
                'latitude' => 0.907000, 'longitude' => 108.988000,
                'koordinat_updated_at' => now(),
                'status_verifikasi' => 'terverifikasi',
                'tanggal_verifikasi' => Carbon::now()->subDays(35),
                'verifikator_id' => 1,
                'catatan_verifikasi' => 'Penghasilan sangat bergantung pada hasil tangkapan',
                'is_active' => true
            ],
            [
                'no_kk' => '6172010101240010',
                'nama_kepala_keluarga' => 'Liem Seng Ho',
                'alamat' => 'Jl. Pahlawan No. 234',
                'rt' => '04', 'rw' => '02',
                'kelurahan' => 'Kuala',
                'kecamatan' => 'Singkawang Tengah',
                'kota' => 'Singkawang',
                'provinsi' => 'Kalimantan Barat',
                'kode_pos' => '79117',
                'status_ekonomi' => 'miskin',
                'penghasilan_bulanan' => 1300000.00,
                'jumlah_anggota' => 3,
                'keterangan' => 'Pemilik warung kecil di kampung',
                'latitude' => 0.910000, 'longitude' => 108.985000,
                'koordinat_updated_at' => now(),
                'status_verifikasi' => 'terverifikasi',
                'tanggal_verifikasi' => Carbon::now()->subDays(28),
                'verifikator_id' => 1,
                'catatan_verifikasi' => 'Usaha kecil dengan modal terbatas',
                'is_active' => true
            ],
            [
                'no_kk' => '6172010101240011',
                'nama_kepala_keluarga' => 'Wong Ah Sing',
                'alamat' => 'Jl. Setapuk Besar No. 156',
                'rt' => '02', 'rw' => '01',
                'kelurahan' => 'Setapuk Besar',
                'kecamatan' => 'Singkawang Utara',
                'kota' => 'Singkawang',
                'provinsi' => 'Kalimantan Barat',
                'kode_pos' => '79155',
                'status_ekonomi' => 'rentan_miskin',
                'penghasilan_bulanan' => 1750000.00,
                'jumlah_anggota' => 6,
                'keterangan' => 'Petani sayur dengan lahan terbatas',
                'latitude' => 0.920000, 'longitude' => 108.970000,
                'koordinat_updated_at' => now(),
                'status_verifikasi' => 'terverifikasi',
                'tanggal_verifikasi' => Carbon::now()->subDays(40),
                'verifikator_id' => 1,
                'catatan_verifikasi' => 'Keluarga besar dengan 4 anak',
                'is_active' => true
            ],
            [
                'no_kk' => '6172010101240012',
                'nama_kepala_keluarga' => 'Siti Mariam',
                'alamat' => 'Jl. Pangmilang No. 78',
                'rt' => '03', 'rw' => '02',
                'kelurahan' => 'Pangmilang',
                'kecamatan' => 'Singkawang Selatan',
                'kota' => 'Singkawang',
                'provinsi' => 'Kalimantan Barat',
                'kode_pos' => '79151',
                'status_ekonomi' => 'miskin',
                'penghasilan_bulanan' => 1150000.00,
                'jumlah_anggota' => 5,
                'keterangan' => 'Buruh cuci baju dengan 3 anak',
                'latitude' => 0.890000, 'longitude' => 108.995000,
                'koordinat_updated_at' => now(),
                'status_verifikasi' => 'terverifikasi',
                'tanggal_verifikasi' => Carbon::now()->subDays(32),
                'verifikator_id' => 1,
                'catatan_verifikasi' => 'Ibu bekerja keras menghidupi keluarga',
                'is_active' => true
            ],
            [
                'no_kk' => '6172010101240013',
                'nama_kepala_keluarga' => 'Chen Wei Ming',
                'alamat' => 'Jl. Bukit Batu No. 99',
                'rt' => '01', 'rw' => '03',
                'kelurahan' => 'Bukit Batu',
                'kecamatan' => 'Singkawang Tengah',
                'kota' => 'Singkawang',
                'provinsi' => 'Kalimantan Barat',
                'kode_pos' => '79117',
                'status_ekonomi' => 'kurang_mampu',
                'penghasilan_bulanan' => 2100000.00,
                'jumlah_anggota' => 4,
                'keterangan' => 'Tukang reparasi elektronik',
                'latitude' => 0.915000, 'longitude' => 108.980000,
                'koordinat_updated_at' => now(),
                'status_verifikasi' => 'terverifikasi',
                'tanggal_verifikasi' => Carbon::now()->subDays(15),
                'verifikator_id' => 1,
                'catatan_verifikasi' => 'Usaha kecil dengan skill khusus',
                'is_active' => true
            ],

            // KABUPATEN SAMBAS (5 keluarga)
            [
                'no_kk' => '6101010101240014',
                'nama_kepala_keluarga' => 'Haji Abdullah',
                'alamat' => 'Jl. Veteran No. 67',
                'rt' => '02', 'rw' => '01',
                'kelurahan' => 'Durian',
                'kecamatan' => 'Sambas',
                'kota' => 'Sambas',
                'provinsi' => 'Kalimantan Barat',
                'kode_pos' => '79462',
                'status_ekonomi' => 'sangat_miskin',
                'penghasilan_bulanan' => 750000.00,
                'jumlah_anggota' => 7,
                'keterangan' => 'Petani dengan lahan terbatas, memiliki banyak tanggungan',
                'latitude' => 1.373000, 'longitude' => 109.297000,
                'koordinat_updated_at' => now(),
                'status_verifikasi' => 'terverifikasi',
                'tanggal_verifikasi' => Carbon::now()->subDays(40),
                'verifikator_id' => 1,
                'catatan_verifikasi' => 'Keluarga besar dengan 5 anak',
                'is_active' => true
            ],
            [
                'no_kk' => '6101010101240015',
                'nama_kepala_keluarga' => 'Siti Khadijah',
                'alamat' => 'Jl. Merdeka No. 145',
                'rt' => '03', 'rw' => '02',
                'kelurahan' => 'Lumbang',
                'kecamatan' => 'Sambas',
                'kota' => 'Sambas',
                'provinsi' => 'Kalimantan Barat',
                'kode_pos' => '79462',
                'status_ekonomi' => 'rentan_miskin',
                'penghasilan_bulanan' => 1600000.00,
                'jumlah_anggota' => 5,
                'keterangan' => 'Janda dengan 3 anak, bekerja sebagai penjahit',
                'latitude' => 1.380000, 'longitude' => 109.290000,
                'koordinat_updated_at' => now(),
                'status_verifikasi' => 'terverifikasi',
                'tanggal_verifikasi' => Carbon::now()->subDays(22),
                'verifikator_id' => 1,
                'catatan_verifikasi' => 'Kepala keluarga perempuan, membutuhkan perhatian khusus',
                'is_active' => true
            ],
            [
                'no_kk' => '6101010101240016',
                'nama_kepala_keluarga' => 'Muhammad Yusuf',
                'alamat' => 'Jl. Sejangkung No. 234',
                'rt' => '01', 'rw' => '03',
                'kelurahan' => 'Sejangkung',
                'kecamatan' => 'Sejangkung',
                'kota' => 'Sambas',
                'provinsi' => 'Kalimantan Barat',
                'kode_pos' => '79453',
                'status_ekonomi' => 'miskin',
                'penghasilan_bulanan' => 1250000.00,
                'jumlah_anggota' => 6,
                'keterangan' => 'Petani padi dengan hasil panen tidak menentu',
                'latitude' => 1.420000, 'longitude' => 109.250000,
                'koordinat_updated_at' => now(),
                'status_verifikasi' => 'terverifikasi',
                'tanggal_verifikasi' => Carbon::now()->subDays(45),
                'verifikator_id' => 1,
                'catatan_verifikasi' => 'Penghasilan bergantung musim panen',
                'is_active' => true
            ],
            [
                'no_kk' => '6101010101240017',
                'nama_kepala_keluarga' => 'Aminah Binti Hasan',
                'alamat' => 'Jl. Teluk Keramat No. 89',
                'rt' => '04', 'rw' => '01',
                'kelurahan' => 'Teluk Keramat',
                'kecamatan' => 'Teluk Keramat',
                'kota' => 'Sambas',
                'provinsi' => 'Kalimantan Barat',
                'kode_pos' => '79465',
                'status_ekonomi' => 'sangat_miskin',
                'penghasilan_bulanan' => 650000.00,
                'jumlah_anggota' => 8,
                'keterangan' => 'Nelayan tradisional dengan perahu kecil',
                'latitude' => 1.450000, 'longitude' => 109.200000,
                'koordinat_updated_at' => now(),
                'status_verifikasi' => 'terverifikasi',
                'tanggal_verifikasi' => Carbon::now()->subDays(50),
                'verifikator_id' => 1,
                'catatan_verifikasi' => 'Keluarga nelayan dengan kondisi sangat terbatas',
                'is_active' => true
            ],
            [
                'no_kk' => '6101010101240018',
                'nama_kepala_keluarga' => 'Pak Usman',
                'alamat' => 'Jl. Samalantan No. 156',
                'rt' => '02', 'rw' => '02',
                'kelurahan' => 'Samalantan',
                'kecamatan' => 'Samalantan',
                'kota' => 'Sambas',
                'provinsi' => 'Kalimantan Barat',
                'kode_pos' => '79466',
                'status_ekonomi' => 'kurang_mampu',
                'penghasilan_bulanan' => 1950000.00,
                'jumlah_anggota' => 4,
                'keterangan' => 'Guru SD dengan istri berjualan kue',
                'latitude' => 1.400000, 'longitude' => 109.270000,
                'koordinat_updated_at' => now(),
                'status_verifikasi' => 'terverifikasi',
                'tanggal_verifikasi' => Carbon::now()->subDays(12),
                'verifikator_id' => 1,
                'catatan_verifikasi' => 'Keluarga dengan penghasilan ganda',
                'is_active' => true
            ],

            // KABUPATEN MEMPAWAH (4 keluarga)
            [
                'no_kk' => '6108010101240019',
                'nama_kepala_keluarga' => 'Pak Joko Widodo',
                'alamat' => 'Jl. Pantai Indah No. 23',
                'rt' => '01', 'rw' => '03',
                'kelurahan' => 'Sungai Pinyuh',
                'kecamatan' => 'Sungai Pinyuh',
                'kota' => 'Mempawah',
                'provinsi' => 'Kalimantan Barat',
                'kode_pos' => '78351',
                'status_ekonomi' => 'kurang_mampu',
                'penghasilan_bulanan' => 2000000.00,
                'jumlah_anggota' => 4,
                'keterangan' => 'Bekerja sebagai buruh pabrik kelapa sawit',
                'latitude' => -0.350000, 'longitude' => 109.180000,
                'koordinat_updated_at' => now(),
                'status_verifikasi' => 'terverifikasi',
                'tanggal_verifikasi' => Carbon::now()->subDays(18),
                'verifikator_id' => 1,
                'catatan_verifikasi' => 'Penghasilan relatif stabil namun masih terbatas',
                'is_active' => true
            ],
            [
                'no_kk' => '6108010101240020',
                'nama_kepala_keluarga' => 'Ibu Mega Sari',
                'alamat' => 'Jl. Nelayan No. 88',
                'rt' => '05', 'rw' => '01',
                'kelurahan' => 'Mempawah Hilir',
                'kecamatan' => 'Mempawah Hilir',
                'kota' => 'Mempawah',
                'provinsi' => 'Kalimantan Barat',
                'kode_pos' => '78361',
                'status_ekonomi' => 'miskin',
                'penghasilan_bulanan' => 1100000.00,
                'jumlah_anggota' => 6,
                'keterangan' => 'Ibu rumah tangga, suami nelayan tradisional',
                'latitude' => -0.370000, 'longitude' => 109.190000,
                'koordinat_updated_at' => now(),
                'status_verifikasi' => 'terverifikasi',
                'tanggal_verifikasi' => Carbon::now()->subDays(32),
                'verifikator_id' => 1,
                'catatan_verifikasi' => 'Keluarga nelayan dengan 4 anak',
                'is_active' => true
            ],
            [
                'no_kk' => '6108010101240021',
                'nama_kepala_keluarga' => 'Bapak Hendra',
                'alamat' => 'Jl. Anjongan No. 67',
                'rt' => '03', 'rw' => '02',
                'kelurahan' => 'Anjongan',
                'kecamatan' => 'Anjongan',
                'kota' => 'Mempawah',
                'provinsi' => 'Kalimantan Barat',
                'kode_pos' => '78352',
                'status_ekonomi' => 'sangat_miskin',
                'penghasilan_bulanan' => 850000.00,
                'jumlah_anggota' => 5,
                'keterangan' => 'Petani karet dengan lahan sempit',
                'latitude' => -0.320000, 'longitude' => 109.160000,
                'koordinat_updated_at' => now(),
                'status_verifikasi' => 'terverifikasi',
                'tanggal_verifikasi' => Carbon::now()->subDays(38),
                'verifikator_id' => 1,
                'catatan_verifikasi' => 'Harga karet fluktuatif mempengaruhi penghasilan',
                'is_active' => true
            ],
            [
                'no_kk' => '6108010101240022',
                'nama_kepala_keluarga' => 'Ibu Sari Dewi',
                'alamat' => 'Jl. Mempawah Hulu No. 234',
                'rt' => '02', 'rw' => '04',
                'kelurahan' => 'Mempawah Hulu',
                'kecamatan' => 'Mempawah Hulu',
                'kota' => 'Mempawah',
                'provinsi' => 'Kalimantan Barat',
                'kode_pos' => '78371',
                'status_ekonomi' => 'rentan_miskin',
                'penghasilan_bulanan' => 1700000.00,
                'jumlah_anggota' => 3,
                'keterangan' => 'Penjual sayur di pasar dengan modal terbatas',
                'latitude' => -0.380000, 'longitude' => 109.170000,
                'koordinat_updated_at' => now(),
                'status_verifikasi' => 'terverifikasi',
                'tanggal_verifikasi' => Carbon::now()->subDays(25),
                'verifikator_id' => 1,
                'catatan_verifikasi' => 'Usaha kecil dengan omset tidak stabil',
                'is_active' => true
            ],

            // KABUPATEN KETAPANG (4 keluarga)
            [
                'no_kk' => '6107010101240023',
                'nama_kepala_keluarga' => 'Bapak Surya Darma',
                'alamat' => 'Jl. Rahadi Usman No. 99',
                'rt' => '02', 'rw' => '02',
                'kelurahan' => 'Mulia Kerta',
                'kecamatan' => 'Delta Pawan',
                'kota' => 'Ketapang',
                'provinsi' => 'Kalimantan Barat',
                'kode_pos' => '78813',
                'status_ekonomi' => 'sangat_miskin',
                'penghasilan_bulanan' => 650000.00,
                'jumlah_anggota' => 8,
                'keterangan' => 'Petani karet dengan lahan sempit, memiliki banyak anak',
                'latitude' => -1.847000, 'longitude' => 109.975000,
                'koordinat_updated_at' => now(),
                'status_verifikasi' => 'terverifikasi',
                'tanggal_verifikasi' => Carbon::now()->subDays(45),
                'verifikator_id' => 1,
                'catatan_verifikasi' => 'Keluarga sangat membutuhkan bantuan dengan 6 anak',
                'is_active' => true
            ],
            [
                'no_kk' => '6107010101240024',
                'nama_kepala_keluarga' => 'Ibu Ratna Dewi',
                'alamat' => 'Jl. Suprapto No. 177',
                'rt' => '04', 'rw' => '03',
                'kelurahan' => 'Sukaharja',
                'kecamatan' => 'Delta Pawan',
                'kota' => 'Ketapang',
                'provinsi' => 'Kalimantan Barat',
                'kode_pos' => '78813',
                'status_ekonomi' => 'rentan_miskin',
                'penghasilan_bulanan' => 1700000.00,
                'jumlah_anggota' => 3,
                'keterangan' => 'Ibu single parent bekerja sebagai guru honorer',
                'latitude' => -1.850000, 'longitude' => 109.980000,
                'koordinat_updated_at' => now(),
                'status_verifikasi' => 'terverifikasi',
                'tanggal_verifikasi' => Carbon::now()->subDays(12),
                'verifikator_id' => 1,
                'catatan_verifikasi' => 'Single parent dengan penghasilan tidak tetap',
                'is_active' => true
            ],
            [
                'no_kk' => '6107010101240025',
                'nama_kepala_keluarga' => 'Pak Bambang',
                'alamat' => 'Jl. Benua Kayong No. 45',
                'rt' => '01', 'rw' => '01',
                'kelurahan' => 'Benua Kayong',
                'kecamatan' => 'Benua Kayong',
                'kota' => 'Ketapang',
                'provinsi' => 'Kalimantan Barat',
                'kode_pos' => '78852',
                'status_ekonomi' => 'miskin',
                'penghasilan_bulanan' => 1200000.00,
                'jumlah_anggota' => 5,
                'keterangan' => 'Nelayan dengan perahu motor kecil',
                'latitude' => -1.780000, 'longitude' => 109.920000,
                'koordinat_updated_at' => now(),
                'status_verifikasi' => 'terverifikasi',
                'tanggal_verifikasi' => Carbon::now()->subDays(30),
                'verifikator_id' => 1,
                'catatan_verifikasi' => 'Hasil tangkapan tidak menentu',
                'is_active' => true
            ],
            [
                'no_kk' => '6107010101240026',
                'nama_kepala_keluarga' => 'Ibu Kartini',
                'alamat' => 'Jl. Sandai No. 123',
                'rt' => '03', 'rw' => '02',
                'kelurahan' => 'Sandai',
                'kecamatan' => 'Sandai',
                'kota' => 'Ketapang',
                'provinsi' => 'Kalimantan Barat',
                'kode_pos' => '78853',
                'status_ekonomi' => 'kurang_mampu',
                'penghasilan_bulanan' => 2150000.00,
                'jumlah_anggota' => 4,
                'keterangan' => 'Pemilik warung sembako kecil',
                'latitude' => -1.820000, 'longitude' => 109.950000,
                'koordinat_updated_at' => now(),
                'status_verifikasi' => 'terverifikasi',
                'tanggal_verifikasi' => Carbon::now()->subDays(20),
                'verifikator_id' => 1,
                'catatan_verifikasi' => 'Usaha kecil dengan modal pas-pasan',
                'is_active' => true
            ],

            // KABUPATEN SANGGAU (4 keluarga)
            [
                'no_kk' => '6105010101240027',
                'nama_kepala_keluarga' => 'Pak Agus Salim',
                'alamat' => 'Jl. Diponegoro No. 55',
                'rt' => '01', 'rw' => '01',
                'kelurahan' => 'Jangkang',
                'kecamatan' => 'Kapuas',
                'kota' => 'Sanggau',
                'provinsi' => 'Kalimantan Barat',
                'kode_pos' => '78557',
                'status_ekonomi' => 'kurang_mampu',
                'penghasilan_bulanan' => 2100000.00,
                'jumlah_anggota' => 5,
                'keterangan' => 'Pegawai honorer dengan istri berjualan di pasar',
                'latitude' => -0.168000, 'longitude' => 110.600000,
                'koordinat_updated_at' => now(),
                'status_verifikasi' => 'terverifikasi',
                'tanggal_verifikasi' => Carbon::now()->subDays(8),
                'verifikator_id' => 1,
                'catatan_verifikasi' => 'Keluarga dengan penghasilan ganda namun masih terbatas',
                'is_active' => true
            ],
            [
                'no_kk' => '6105010101240028',
                'nama_kepala_keluarga' => 'Bapak Dayak Taman',
                'alamat' => 'Jl. Tayan Hilir No. 89',
                'rt' => '02', 'rw' => '03',
                'kelurahan' => 'Tayan Hilir',
                'kecamatan' => 'Tayan Hilir',
                'kota' => 'Sanggau',
                'provinsi' => 'Kalimantan Barat',
                'kode_pos' => '78558',
                'status_ekonomi' => 'sangat_miskin',
                'penghasilan_bulanan' => 700000.00,
                'jumlah_anggota' => 7,
                'keterangan' => 'Petani ladang berpindah suku Dayak',
                'latitude' => -0.200000, 'longitude' => 110.550000,
                'koordinat_updated_at' => now(),
                'status_verifikasi' => 'terverifikasi',
                'tanggal_verifikasi' => Carbon::now()->subDays(55),
                'verifikator_id' => 1,
                'catatan_verifikasi' => 'Keluarga adat dengan kondisi ekonomi sangat terbatas',
                'is_active' => true
            ],
            [
                'no_kk' => '6105010101240029',
                'nama_kepala_keluarga' => 'Ibu Maria Ulina',
                'alamat' => 'Jl. Sekayam No. 234',
                'rt' => '04', 'rw' => '01',
                'kelurahan' => 'Sekayam',
                'kecamatan' => 'Sekayam',
                'kota' => 'Sanggau',
                'provinsi' => 'Kalimantan Barat',
                'kode_pos' => '78559',
                'status_ekonomi' => 'miskin',
                'penghasilan_bulanan' => 1350000.00,
                'jumlah_anggota' => 6,
                'keterangan' => 'Penenun kain tradisional Dayak',
                'latitude' => -0.250000, 'longitude' => 110.650000,
                'koordinat_updated_at' => now(),
                'status_verifikasi' => 'terverifikasi',
                'tanggal_verifikasi' => Carbon::now()->subDays(42),
                'verifikator_id' => 1,
                'catatan_verifikasi' => 'Kerajinan tradisional dengan pasar terbatas',
                'is_active' => true
            ],
            [
                'no_kk' => '6105010101240030',
                'nama_kepala_keluarga' => 'Pak Antonius',
                'alamat' => 'Jl. Balai Karangan No. 67',
                'rt' => '03', 'rw' => '02',
                'kelurahan' => 'Balai Karangan',
                'kecamatan' => 'Balai Karangan',
                'kota' => 'Sanggau',
                'provinsi' => 'Kalimantan Barat',
                'kode_pos' => '78560',
                'status_ekonomi' => 'rentan_miskin',
                'penghasilan_bulanan' => 1800000.00,
                'jumlah_anggota' => 4,
                'keterangan' => 'Tukang kayu dengan pesanan tidak tetap',
                'latitude' => -0.180000, 'longitude' => 110.580000,
                'koordinat_updated_at' => now(),
                'status_verifikasi' => 'terverifikasi',
                'tanggal_verifikasi' => Carbon::now()->subDays(28),
                'verifikator_id' => 1,
                'catatan_verifikasi' => 'Skill khusus namun pesanan tidak stabil',
                'is_active' => true
            ],

            // KABUPATEN SINTANG (4 keluarga)
            [
                'no_kk' => '6104010101240031',
                'nama_kepala_keluarga' => 'Bapak Dayak Iban',
                'alamat' => 'Jl. Veteran No. 123',
                'rt' => '03', 'rw' => '02',
                'kelurahan' => 'Kapuas Kanan Hilir',
                'kecamatan' => 'Sintang',
                'kota' => 'Sintang',
                'provinsi' => 'Kalimantan Barat',
                'kode_pos' => '78619',
                'status_ekonomi' => 'sangat_miskin',
                'penghasilan_bulanan' => 700000.00,
                'jumlah_anggota' => 6,
                'keterangan' => 'Petani tradisional suku Dayak dengan lahan terbatas',
                'latitude' => 0.063000, 'longitude' => 111.500000,
                'koordinat_updated_at' => now(),
                'status_verifikasi' => 'terverifikasi',
                'tanggal_verifikasi' => Carbon::now()->subDays(50),
                'verifikator_id' => 1,
                'catatan_verifikasi' => 'Keluarga adat dengan kondisi ekonomi sangat terbatas',
                'is_active' => true
            ],
            [
                'no_kk' => '6104010101240032',
                'nama_kepala_keluarga' => 'Ibu Dayak Kanayatn',
                'alamat' => 'Jl. Dedai No. 89',
                'rt' => '01', 'rw' => '03',
                'kelurahan' => 'Dedai',
                'kecamatan' => 'Dedai',
                'kota' => 'Sintang',
                'provinsi' => 'Kalimantan Barat',
                'kode_pos' => '78654',
                'status_ekonomi' => 'miskin',
                'penghasilan_bulanan' => 1250000.00,
                'jumlah_anggota' => 5,
                'keterangan' => 'Penjual hasil hutan dan kerajinan rotan',
                'latitude' => 0.100000, 'longitude' => 111.450000,
                'koordinat_updated_at' => now(),
                'status_verifikasi' => 'terverifikasi',
                'tanggal_verifikasi' => Carbon::now()->subDays(35),
                'verifikator_id' => 1,
                'catatan_verifikasi' => 'Bergantung pada hasil hutan musiman',
                'is_active' => true
            ],
            [
                'no_kk' => '6104010101240033',
                'nama_kepala_keluarga' => 'Pak Melayu Sintang',
                'alamat' => 'Jl. Kelam Permai No. 156',
                'rt' => '02', 'rw' => '01',
                'kelurahan' => 'Kelam Permai',
                'kecamatan' => 'Kelam Permai',
                'kota' => 'Sintang',
                'provinsi' => 'Kalimantan Barat',
                'kode_pos' => '78652',
                'status_ekonomi' => 'rentan_miskin',
                'penghasilan_bulanan' => 1650000.00,
                'jumlah_anggota' => 4,
                'keterangan' => 'Nelayan sungai dengan perahu tradisional',
                'latitude' => 0.080000, 'longitude' => 111.480000,
                'koordinat_updated_at' => now(),
                'status_verifikasi' => 'terverifikasi',
                'tanggal_verifikasi' => Carbon::now()->subDays(40),
                'verifikator_id' => 1,
                'catatan_verifikasi' => 'Hasil tangkapan bergantung musim air',
                'is_active' => true
            ],
            [
                'no_kk' => '6104010101240034',
                'nama_kepala_keluarga' => 'Bapak Sepauk',
                'alamat' => 'Jl. Sepauk No. 234',
                'rt' => '04', 'rw' => '02',
                'kelurahan' => 'Sepauk',
                'kecamatan' => 'Sepauk',
                'kota' => 'Sintang',
                'provinsi' => 'Kalimantan Barat',
                'kode_pos' => '78653',
                'status_ekonomi' => 'kurang_mampu',
                'penghasilan_bulanan' => 2050000.00,
                'jumlah_anggota' => 3,
                'keterangan' => 'Pegawai desa dengan istri guru TK',
                'latitude' => 0.120000, 'longitude' => 111.520000,
                'koordinat_updated_at' => now(),
                'status_verifikasi' => 'terverifikasi',
                'tanggal_verifikasi' => Carbon::now()->subDays(15),
                'verifikator_id' => 1,
                'catatan_verifikasi' => 'Penghasilan relatif stabil namun terbatas',
                'is_active' => true
            ],

            // KABUPATEN KAPUAS HULU (3 keluarga)
            [
                'no_kk' => '6103010101240035',
                'nama_kepala_keluarga' => 'Kepala Suku Dayak',
                'alamat' => 'Jl. Lintas Utara No. 44',
                'rt' => '02', 'rw' => '01',
                'kelurahan' => 'Putussibau Utara',
                'kecamatan' => 'Putussibau Utara',
                'kota' => 'Kapuas Hulu',
                'provinsi' => 'Kalimantan Barat',
                'kode_pos' => '78711',
                'status_ekonomi' => 'miskin',
                'penghasilan_bulanan' => 950000.00,
                'jumlah_anggota' => 7,
                'keterangan' => 'Pemimpin adat dengan tanggung jawab sosial tinggi namun ekonomi terbatas',
                'latitude' => 0.853000, 'longitude' => 112.937000,
                'koordinat_updated_at' => now(),
                'status_verifikasi' => 'terverifikasi',
                'tanggal_verifikasi' => Carbon::now()->subDays(60),
                'verifikator_id' => 1,
                'catatan_verifikasi' => 'Tokoh masyarakat dengan keluarga besar',
                'is_active' => true
            ],
            [
                'no_kk' => '6103010101240036',
                'nama_kepala_keluarga' => 'Bapak Embaloh',
                'alamat' => 'Jl. Embaloh Hulu No. 67',
                'rt' => '01', 'rw' => '02',
                'kelurahan' => 'Embaloh Hulu',
                'kecamatan' => 'Embaloh Hulu',
                'kota' => 'Kapuas Hulu',
                'provinsi' => 'Kalimantan Barat',
                'kode_pos' => '78751',
                'status_ekonomi' => 'sangat_miskin',
                'penghasilan_bulanan' => 600000.00,
                'jumlah_anggota' => 8,
                'keterangan' => 'Petani ladang berpindah di pedalaman',
                'latitude' => 0.900000, 'longitude' => 112.800000,
                'koordinat_updated_at' => now(),
                'status_verifikasi' => 'terverifikasi',
                'tanggal_verifikasi' => Carbon::now()->subDays(65),
                'verifikator_id' => 1,
                'catatan_verifikasi' => 'Lokasi terpencil dengan akses terbatas',
                'is_active' => true
            ],
            [
                'no_kk' => '6103010101240037',
                'nama_kepala_keluarga' => 'Ibu Dayak Taman',
                'alamat' => 'Jl. Batang Lupar No. 123',
                'rt' => '03', 'rw' => '01',
                'kelurahan' => 'Batang Lupar',
                'kecamatan' => 'Batang Lupar',
                'kota' => 'Kapuas Hulu',
                'provinsi' => 'Kalimantan Barat',
                'kode_pos' => '78752',
                'status_ekonomi' => 'rentan_miskin',
                'penghasilan_bulanan' => 1550000.00,
                'jumlah_anggota' => 5,
                'keterangan' => 'Penjual hasil hutan dan ikan sungai',
                'latitude' => 0.950000, 'longitude' => 112.850000,
                'koordinat_updated_at' => now(),
                'status_verifikasi' => 'terverifikasi',
                'tanggal_verifikasi' => Carbon::now()->subDays(45),
                'verifikator_id' => 1,
                'catatan_verifikasi' => 'Penghasilan bergantung hasil hutan',
                'is_active' => true
            ],

            // KABUPATEN BENGKAYANG (3 keluarga)
            [
                'no_kk' => '6107010101240038',
                'nama_kepala_keluarga' => 'Pak Dayak Bidayuh',
                'alamat' => 'Jl. Bengkayang No. 89',
                'rt' => '01', 'rw' => '01',
                'kelurahan' => 'Bumi Emas',
                'kecamatan' => 'Bengkayang',
                'kota' => 'Bengkayang',
                'provinsi' => 'Kalimantan Barat',
                'kode_pos' => '79213',
                'status_ekonomi' => 'miskin',
                'penghasilan_bulanan' => 1300000.00,
                'jumlah_anggota' => 6,
                'keterangan' => 'Petani karet dan padi dengan lahan terbatas',
                'latitude' => 0.850000, 'longitude' => 109.450000,
                'koordinat_updated_at' => now(),
                'status_verifikasi' => 'terverifikasi',
                'tanggal_verifikasi' => Carbon::now()->subDays(35),
                'verifikator_id' => 1,
                'catatan_verifikasi' => 'Keluarga Dayak dengan tradisi pertanian',
                'is_active' => true
            ],
            [
                'no_kk' => '6107010101240039',
                'nama_kepala_keluarga' => 'Ibu Ledo Sari',
                'alamat' => 'Jl. Ledo No. 156',
                'rt' => '02', 'rw' => '03',
                'kelurahan' => 'Ledo',
                'kecamatan' => 'Ledo',
                'kota' => 'Bengkayang',
                'provinsi' => 'Kalimantan Barat',
                'kode_pos' => '79254',
                'status_ekonomi' => 'kurang_mampu',
                'penghasilan_bulanan' => 1950000.00,
                'jumlah_anggota' => 4,
                'keterangan' => 'Pemilik warung sembako di perbatasan',
                'latitude' => 0.880000, 'longitude' => 109.480000,
                'koordinat_updated_at' => now(),
                'status_verifikasi' => 'terverifikasi',
                'tanggal_verifikasi' => Carbon::now()->subDays(20),
                'verifikator_id' => 1,
                'catatan_verifikasi' => 'Usaha di daerah perbatasan dengan omset terbatas',
                'is_active' => true
            ],
            [
                'no_kk' => '6107010101240040',
                'nama_kepala_keluarga' => 'Bapak Jagoi',
                'alamat' => 'Jl. Jagoi Babang No. 234',
                'rt' => '03', 'rw' => '02',
                'kelurahan' => 'Jagoi',
                'kecamatan' => 'Jagoi Babang',
                'kota' => 'Bengkayang',
                'provinsi' => 'Kalimantan Barat',
                'kode_pos' => '79255',
                'status_ekonomi' => 'sangat_miskin',
                'penghasilan_bulanan' => 750000.00,
                'jumlah_anggota' => 7,
                'keterangan' => 'Buruh tani dengan keluarga besar',
                'latitude' => 0.920000, 'longitude' => 109.500000,
                'koordinat_updated_at' => now(),
                'status_verifikasi' => 'terverifikasi',
                'tanggal_verifikasi' => Carbon::now()->subDays(48),
                'verifikator_id' => 1,
                'catatan_verifikasi' => 'Keluarga besar dengan penghasilan sangat terbatas',
                'is_active' => true
            ]
        ];

        foreach ($keluargaData as $data) {
            // Set lokasi Point jika ada koordinat (sudah dihandle oleh boot method di model)
            if (isset($data['latitude']) && isset($data['longitude'])) {
                $data['lokasi'] = new Point($data['latitude'], $data['longitude']);
            }

            Keluarga::create($data);
        }

        $this->command->info('Seeder KeluargaKalbar berhasil dijalankan dengan ' . count($keluargaData) . ' data keluarga.');
    }
}
